name = "MyFirstPackage"
uuid = "14eee9a3-be42-4cc6-95b1-14fbfb6925ea"
authors = ["James Quinlan"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
